name: pyapprox-dev
channels:
  - conda-forge
  - defaults
dependencies:
#  - python=3.7 # when using with CI matrix this creates conflicts
  - python
  - numpy=1.19.2
  - numba
  - jupyter
  - pytest
  - pytest-cov
  - pip
  - setuptools
  - scikit-learn
  - pymc3
  - Cython
  - seaborn
  - sympy
  - matplotlib
  - fenics=2019
  - mshr
  - scipy=1.3.1
  - networkx
  # make html in docs folder
  - sphinx
  - sphinx-gallery
  - pip:
    - sphinx_copybutton
    - sphinx_rtd_theme
    - numpydoc
    - sphinx_automodapi