[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools",
    "wheel",
    "Cython",
    "numpy>=1.19.3",
    "scipy>=1.0.0"]
#cython is needed for build to execute because some of Pyapprox cython extensions use
#scipy cython functions