name: PyApprox CI - conda

on:
  push:
    branches:
      - master

  workflow_dispatch:


#   # schedule:
#   #  # * is a special character in YAML so you have to quote this string
#   #  - cron:  '*/0 * * * *' # run once a day


jobs:
  pyapprox_unit_tests:
    name: Setup Pyapprox dependencies with conda
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6]
#        os: [ubuntu-latest, macos-latest, windows-latest]
#        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: pyapprox-dev
          python-version: ${{ matrix.python-version }}
          channels: defaults,conda-forge
          environment-file: environment.yml
          use-only-tar-bz2: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Setup PyApprox
      run: |
        pip install -e .
    - name: Test PyApprox
      run: |
        python setup.py test
    - name: Setup PyApprox Documentation
      run: |
        pip install -e .[docs]
    - name: Create PyApprox Documentation
      run: |
        cd docs
        make html
      
      