name: GitHub CI - PyApprox

on:
  push:
    branches:
      - master

  workflow_dispatch:


#   # schedule:
#   #  # * is a special character in YAML so you have to quote this string
#   #  - cron:  '*/0 * * * *' # run once a day


jobs:
  pyapprox_unit_tests:
    name: Setup Pyapprox dependencies with conda
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.5]
#        os: [ubuntu-latest, macos-latest, windows-latest]
#        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup PyApprox
      run: |
        python setup.py develop
    - name: Test PyApprox
      run: |
        pytest
      